### ISSUE TITLE
Pre-built binaries?

### ISSUE THREAD

**Issue by dariomanesku** [xelatihy/yocto-gl#1]
Why don't you add pre-built binaries for people that just want to try it out without bothering to compile the apps?

**Comment by xelatihy** [comment]
The apps are not supported. They are just example of library usage. Just like github.com/nothings/stb.
Plus making OpenGL work on many platform is really painful, sadly and takes more times than the actual core library development.

I'll close this one since it won't happen for a while.

**Comment by xelatihy** [comment]
yocto/GL won't support prebuilt binaries.
