### ISSUE TITLE
Question: Can ysr_init_scene be safely called repeatedly?

### ISSUE THREAD

**Issue by Kazade** [xelatihy/yocto-gl#10]
Sorry for using the issue tracker for a question. 

I noticed that `ysr_init_scene` takes the number of bodies to be simulated, but in my use case I don't know how many will be needed at the time the scene is created. Looking at the code of that function it seems that calling `ysr_init_scene` repeatedly with a higher `nbodies` value shouldn't cause an issue, I just wondered if you could tell me whether that was safe or not?

Thanks, and thanks for such an awesomely simple physics library :)

**Comment by xelatihy** [comment]
yes you can, but it won't be optimal.
i can probably add a method to add objects if you want, but it will have to wait sometime.
