### ISSUE TITLE
Missing include in yocto_gui.cpp and Embree enabled by default

### ISSUE THREAD

**Issue by AbdullrahmanAlzeidi** [xelatihy/yocto-gl#1001]
Hello

I ran into two (easily fixable) problems while building the library for the first time.

1. Missing `#include <atomic>` in yocto_gui.cpp, adding the include fxed this immediately.

2. Trying to link with Embree by default. The README page did not say that linking is enabled by default, this caused the build to fail and I had to manually change the `YOCTO_EMBREE` flag in the CMakeLists.txt file to not build with it.

**Comment by xelatihy** [comment]
Thanks. Just fixed it.
