### ISSUE TITLE
Save in glTF format

### ISSUE THREAD

**Issue by kaiyeh0913** [xelatihy/yocto-gl#1086]
Hi,
Thank you all for this wonderful PBR library. I found an issue with exporting glTF file.

I saw the document said that it could load and save glTF but it seems like there is no function for exporting scenes in glTF format. I was wondering if this function coming up anytime soon or is there any way I could integrate with this library? Thank you so much.

**Comment by xelatihy** [comment]
It is not supported now. It is a documentation bug. But I will likely add it in the coming days.

**Comment by kaiyeh0913** [comment]
Thanks for the explanation and looking forward to that anytime soon!

**Comment by xelatihy** [comment]
Se have a very preliminary version for this. Th real issues is that textures are hard to get correct since glTF use packing while we do not. For now, most things should work fine, except some texture packing and the camera fov. I am closing this issue for now.
