### ISSUE TITLE
Bug in compute_moments?

### ISSUE THREAD

**Issue by tkoolen** [xelatihy/yocto-gl#12]
https://github.com/xelatihy/yocto-gl/blob/079a7ce3dd2492ca0cc3977de23e014e37b5184f/yocto/yocto_sym.h#L367

Shouldn't the right hand side be `inertia[1][2]`?

Note that I haven't actually used your code, was just browsing the code.

**Comment by xelatihy** [comment]
I am closing this since it is fixed in the current release.
