### ISSUE TITLE
Denoise not optimised

### ISSUE THREAD

**Issue by M1ndHunteR** [xelatihy/yocto-gl#1228]
Hi there, 
great project!

I compiled yscene with denoise option which is effective.
It doesn't look to be efficient though. For testing purposes i use _.\yscene.exe view .\tool\materials1.json_
When I enable denoise checkbox, the noise disappears, but processing speed drops SUPER dramatically and takes ~10 times longer.
However, if i keep denoise UNCHECKED until very last cycle, and then enable it - the end result is great, same as it is when denoise kept enable throughout all cycles, while processing speed remains OK.
Obviously, I cannot sit there and keep enabling and disabling the checkbox for every image I render.

I am doing something wrong?

Thanks a lot,
Gene.

**Comment by xelatihy** [comment]
You are doing things right. There is a tradeoff thought that I should explain.

1. for small scenes you would like to run a batch of samples and then denoise once
2. for large scenes, even running one sample is expensive, so you want to denoise each sample

Right now yocto is optimized for large scenes and runs one sample at a time.

What I could do is to add an option to run more samples per batch. This is straightforward to do in the current architecture and there are no drawbacks. I would still leave the one sample default, but you would be able to change the batch size in the command line and UI.

Would this solve your problem?

**Comment by M1ndHunteR** [comment]
Hi Fabio,
Thanks for your reply.

> Would this solve your problem?

Yes, it definitely will. Thanks a lot.

**Comment by xelatihy** [comment]
There is initial support implemented in #1230 which is merged in the main branch. The implement is rough by functional. Let see how well it works.
