### ISSUE TITLE
New sampler type to run the furnace test

### ISSUE THREAD

**Issue by dsforza96** [xelatihy/yocto-gl#1235]

**Comment by xelatihy** [comment]
I will add two more samplers to the path tracer. One sampler will follow integrate over the environment without environment sampling and shadows. The other will integrate direct illumination with mis.

**Comment by dsforza96** [comment]
After running a furnace test with a custom shader, it seems that there is some loss of energy in the case of polished conductors.

**Comment by xelatihy** [comment]
Fixed in #1259
