### ISSUE TITLE
save_gltf_scene() is not working

### ISSUE THREAD

**Issue by Hurleyworks** [xelatihy/yocto-gl#1308]
save_gltf_scene() doesn't seem to be working in the latest version on github

line 4898 of yocto_sceneio.cpp triggers an error
error: [json.exception.type_error.311] cannot use emplace_back() with number

Easy way to test is to just load a .gltf  file and try to save it after loading in run_view()
```
  auto scene = load_scene(params.scene);
  print_info("load scene: {}", elapsed_formatted(timer));

  const std::string out("C:/Users/micro/Desktop/yocto/test.gltf");
  save_scene(out, scene);
```

**Comment by xelatihy** [comment]
We'll look into this ASAP.

**Comment by xelatihy** [comment]
Move to use external library in main branch. Still WIP, but should not crash. I am closing this for now.
