### ISSUE TITLE
Library usage with CMake

### ISSUE THREAD

**Issue by f-fanni** [xelatihy/yocto-gl#1310]
Hi, trying to set up a project including this library with `add_subdirectory(ext/yocto-gl)` gives a few errors.

1. In file yocto_mesh.cpp, at line 178 and forward there are three calls to isnan, which is not declared in the scope. Setting `using std::isnan` in the previous line fix the issue.
2. In the "main" cmake file the usage of option to set the yocto variables, together with the version 3.12, causes any previously set value to be obscured. A version bump to 3.13 is enough to fix it.
3. It would also be nice to an additional option to exclude the building of the apps when using as lib only, to do something like: 
```
option(YOCTO_APPS "Build apps" ON)
...
if(YOCTO_APPS)
  add_subdirectory(apps)
endif(YOCTO_APPS)
```
4. I had to add a `target_include_directories(yocto PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/..") in` the cmake file in libs/yocto/ to be able to include any header from the library.

**Comment by xelatihy** [comment]
Fixed in #1317
