### ISSUE TITLE
Turn public low level path tracing functions/structures

### ISSUE THREAD

**Issue by mkanada** [xelatihy/yocto-gl#1311]
I'm creating (again) one adaptive sampling trace based in this great software. But I just want to use this as a library and not modify your code. To do so, I need some low level functions/structures be public in 'yocto_pathtrace.h'.

struct trace_result {
  vec3f radiance = {0, 0, 0};
  bool  hit      = false;
  vec3f albedo   = {0, 0, 0};
  vec3f normal   = {0, 0, 0};
};

ray3f sample_camera(const camera_data& camera, const vec2i& ij,
    const vec2i& image_size, const vec2f& puv, const vec2f& luv, bool tent);

using sampler_func = trace_result (*)(const scene_data& scene,
    const scene_bvh& bvh, const trace_lights& lights, const ray3f& ray,
    rng_state& rng, const trace_params& params);

sampler_func get_trace_sampler_func(const trace_params& params);

static trace_result trace_path(const scene_data& scene, const scene_bvh& bvh,
    const trace_lights& lights, const ray3f& ray_, rng_state& rng,
    const trace_params& params);

Thanks again by your great software.

**Comment by xelatihy** [comment]
Make sense. I'll do this in the next release.

**Comment by xelatihy** [comment]
Listed in #1375
