### ISSUE TITLE
Is embree working?

### ISSUE THREAD

**Issue by mkanada** [xelatihy/yocto-gl#1312]
Linux, libembree3.so.3.13.2

yscene view --embreebvh

![Screenshot from 2021-12-29 06-57-12](https://user-images.githubusercontent.com/14933941/147650304-ad47b1bd-7bcc-44a7-aae1-b3b58fcd7822.png)

yscene view (without embreebvh)

![Screenshot from 2021-12-29 06-58-10](https://user-images.githubusercontent.com/14933941/147650336-da61549f-7017-458e-a3ea-e839046f9260.png)

**Comment by xelatihy** [comment]
I'll test it soon.

**Comment by xelatihy** [comment]
Embree works on my build and is tested on Windows and Mac. 
Can you let me know more information on how to reproduce it?

**Comment by mkanada** [comment]
I'm using ArchLinux, so with (usually) more recents libraries. I dont have Windows and/or Mac.

**Comment by mkanada** [comment]
It is a problem with parallelism. 

in yocto_gui.cpp:680

`        //parallel_for(state.width, state.height, [&](int i, int j) {
        for(int i = 0; i < state.width; i++) {
          for(int j = 0; j < state.height; j++) {
          for (auto s = 0; s < params.batch; s++) {
            if (render_stop) return;
            trace_sample(state, scene, bvh, lights, i, j, params);
          }
          }
        }
        //});

`
The program 'yscene' works correctly, but (obviously) slower.

I will continue to the problem.

**Comment by mkanada** [comment]
I found it.  Please add '  embree_ray.ray.mask      = -1;  ' in yocto_bvh.cpp in lines 302 and 328.

**Comment by xelatihy** [comment]
I am still not able to reproduce it. But I made the change you suggested in main.
