### ISSUE TITLE
How to build for arm board

### ISSUE THREAD

**Issue by anantha-vidhya** [xelatihy/yocto-gl#1336]
Hi Everyone,
I had here few doubts 
1. How to build opengl package from scratch for arm board.
2. Cross-compiler tool chain i had is TI's SDK Linux-devkit (Hope you aware of).
Please can you mention me detailed steps in achieving this.
Thanks & Regards
A.N.V.Lavanya

**Comment by xelatihy** [comment]
I do not have any such hardware and I suspect it won't work there without changes. This is mostly won't fix, but I'll leave it here to see if others have suggestions.

**Comment by anantha-vidhya** [comment]
OK fine, Thank you .
But i cannot even find opengl source code to build at least for desktop.
Can you help me about how to build opengl for desktop so that i will try to modify things compatable to arm board.
Also had a small doubt how i get source code for opengl. I am confused of too many chains what exactly and where exactly i should download opengl.
Thanks & Regards
A.N.V.Lavanya

**Comment by xelatihy** [comment]
Closing this since I do not know how to help.
