### ISSUE TITLE
Vector index error when bvh process.

### ISSUE THREAD

**Issue by yohawing** [xelatihy/yocto-gl#1384]
It makes triangle vector array below.
yocto_modelio.h:632
`triangles.push_back({get_value<T>(prop, current + 0), (T)-1, (T)-1});`

But, bvh process uses triangle y,z (-1)
yocto_bvh.cpp:344
`bboxes[idx]    = triangle_bounds(shape.positions[triangle.x],
             shape.positions[triangle.y], shape.positions[triangle.z]);`
             
It makes out of index error when import models.

**Comment by xelatihy** [comment]
Cannot reproduce. Close for now.
