### ISSUE TITLE
Compilation error at std::array initialization

### ISSUE THREAD

**Issue by syoyo** [xelatihy/yocto-gl#14]
gcc 5.4 does not accept `a = {}` initialization for std::array.
(and clang will report it as warning when increasing warning level(e.g. `-Wall`))

```
$ g++ -std=c++11 yocto_gltf.h
yocto_gltf.h:615:55: error: array must be initialized with a brace-enclosed initializer
     std::array<float, 4> baseColorFactor = {1, 1, 1, 1};
```

More C++11 compliant solution is

```
std::array<float, 4> baseColorFactor{{1, 1, 1, 1}}; // OK
```

**Comment by xelatihy** [comment]
I am normally compiling with C++14, which is why I did not notice it. I can try to track this down in the next few days.

**Comment by xelatihy** [comment]
How important is support for c++11? I looked at all of yocto and c++14 helps a lot. I could switch many c++14 features off, but I am not sure what is the real gain. What do you think?

**Comment by syoyo** [comment]
Since there is no explicit description about C++ compiler requirement, thus I was just expected that Yocto is compilable with C++11 compiler.

Supporting only C++14 or later would be OK. In such a case it would be better to describe it in `README.md`
(FYI, old environment such like RHEL6 supports up to C++11(gcc 4.8.1))

**Comment by Teybeo** [comment]
Yeah, like syoyo said, adding C++ version requirement would be nice.
I just got left scratching my head about this error, using Clion, default is C++11

**Comment by xelatihy** [comment]
This particular bug is fixed in the development branch since I remove std::array everywhere.
Also the development branch compiles on clang as C++11. I will close this.

**Comment by syoyo** [comment]
Cool! Thanks!
