### ISSUE TITLE
make_rounded_uvcylinder segmentation fault

### ISSUE THREAD

**Issue by podd0** [xelatihy/yocto-gl#1417]
The function does access on `shape.normals`, which is empty (maybe this is the actual error). I tried adding the line `shape.normals.resize(shape.positions.size());`, but the generated model looks like this 
![Screenshot from 2022-12-22 16-40-39](https://user-images.githubusercontent.com/44962199/209170231-432278ea-2750-4cbe-a419-855216061f46.png)

**Comment by xelatihy** [comment]
This bug will not be fixed in the main release, which is frozen now. I will fix it in the coming one.
