### ISSUE TITLE
Reload cuscene error

### ISSUE THREAD

**Issue by TerminalTitanium** [xelatihy/yocto-gl#1435]
Hello!

I apologize for my inexperience. I am just learning. There was a need to add objects to the cuscene. During the recalculation of data, the program crashes with an error. I have tested this feature in CPU Trace on mac. There were no problems. Then I decided to move code to MSVC Windows 10 with cuda because of perfomance. I use example from cutrace.
1. Loaded Cutrace example OK
2. Add simple button GUI that added new mesh to scene.
3. When I press button I have an error.

Code button:
`
auto shape_model_2 = shape_data{};
  string filename_2 = "example.stl";
  auto error = string{};
  if(!load_shape(filename_2, shape_model_2, error))
      print_error(error);
  scene.shapes.push_back(shape_model_2);

  auto instance_2 = instance_data{};
  instance_2.frame = {{1,0,0},{0,1,0},{0,0,1},{0,0,0}};
  instance_2.shape = 3;
  instance_2.material = 3;

  scene.instances.push_back(instance_2);
  context = make_cutrace_context(params);
  cuscene = make_cutrace_scene(context, scene, params);
  bvh = make_cutrace_bvh(context, cuscene, params);
  lights = make_cutrace_lights(context, scene, params);
  state = make_cutrace_state(context, scene, params);
  pstate    = make_cutrace_state(context, scene, pparams);
`
  
  Error
  Exception at 0x7ffd17cbcf19, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at C:\Users\HyperPC\Projects\yocto-gl-main\libs\yocto\yocto_cutrace.cpp:55

Error name: CUDA_ERROR_INVALID_VALUE (1)

<img width="793" alt="Screenshot 2023-06-14 at 00 11 50" src="https://github.com/xelatihy/yocto-gl/assets/31609285/d9696e2b-
<img width="1403" alt="Screenshot 2023-06-14 at 00 12 40" src="https://github.com/xelatihy/yocto-gl/assets/31609285/f0d8ca7d-7039-4ea0-a2d3-2a141be70a23">
900e-4850-be1d-4d2453869645">
<img width="1408" alt="Screenshot 2023-06-14 at 00 13 13" src="https://github.com/xelatihy/yocto-gl/assets/31609285/23011b8b-86ba-4da1-8686-331769cbb0ba">

**Comment by TerminalTitanium** [comment]
I would be very grateful for any help in solving this problem

**Comment by TerminalTitanium** [comment]
I think we need to create new functions like update_cutrace_cameras. For example update_cutrace_shapes, update_cutrace_instances.

I can rotate mesh or camera on CPU, but I can rotate only camera while on GPU
Here some code of animation 360:
```
auto funcRotation = [](float angle, float o_x, float o_y, float radius_x, float radius_y)
  {
        float rad_angle = angle/rad;
        float point_x = o_x + radius_x * std::cos(rad_angle);
        float point_y = o_y + radius_y * std::sin(rad_angle);
        return vec2f{point_x,point_y};
    };

for (int i=0; i<steps; ++i)
 {
        vec2f coord_xz = funcRotation(angle,0,0,radius_x,radius_y);
        angle += angle_step;

        //*** CAMERA ROTATION***
        auto &cur_camera = _scene.cameras[0];
        cur_camera.frame = lookat_frame({coord_xz.x, 0, coord_xz.y},{0,0,0},{0,1,0});
        //*** MESH ROTATION work only with CPU***
        //auto &cur_instanse = _scene.instances[0];
        //cur_instanse.frame = lookat_frame({0, 0, 0},{coord_xz.x,0,coord_xz.y},{0,1,0});

#ifdef YOCTO_CUDA
        update_cutrace_cameras(_context,_cuscene,_scene,_params);
        reset_cutrace_state(_context,_state,_scene,_params);
        trace_start(_context, _state, _cuscene, _bvh, _lights, _scene, _params);
#else
        _state = make_trace_state(_scene, _params);
#endif

        for (auto sample : range(0, _params.samples, _params.batch))
        {
            auto sample_timer = simple_timer{};
#ifdef YOCTO_CUDA
            trace_samples(_context, _state, _cuscene, _bvh, _lights, _scene, _params);
#else
            trace_samples(_state, _scene, _bvh, _lights, _params);
#endif
            print_info("render sample {}/{}: {}", _state.samples, _params.samples, elapsed_formatted(sample_timer));
        }
        print_info("IMAGE render image: {}/{}", i+1, _rp.steps);
}
```

**Comment by TerminalTitanium** [comment]
So we can add or change shapes on CPU, but we can't add or change shapes on GPU. if i'm wrong, please guide me

**Comment by xelatihy** [comment]
Yes you are right. Shapes on GPU are fixed. On CPU you can only make small changes.

In general, the system is written under the assumption that the Bvh/Light gets fully rebuild on scene changes though. This is unlikely to change in the future since we optimize for large scene rendering and not interactive applications.
