### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by chudonghao** [xelatihy/yocto-gl#17]
/home/xxx/Gits/yocto-gl/bin/yshade car.gltf
Signal: SIGSEGV (Segmentation fault)

**Comment by xelatihy** [comment]
Is the model car.gltf available somewhere? 

Note that gltf 2.0 is still in draft and the spec is changing so often that I have decided to keep it in synch only after a stable draft is ready.

**Comment by chudonghao** [comment]
of course,the example glview of tinygltfloader does well.

**Comment by xelatihy** [comment]
Hopefully fixed in the development branch.
