### ISSUE TITLE
ygltf::fl_gltf leaks memory

### ISSUE THREAD

**Issue by KageKirin** [xelatihy/yocto-gl#18]
Hi,

while parsing your code, I found that the structure `fl_gltf` is bound to leak memory when destroyed because all of it member vectors contain unmanaged pointers.

Expected behaviour: not leak any memory, ever.

While there are a number of ways to solve this, I'd just recommend you turn the pointers into flat variables.

Best regards.

**Comment by xelatihy** [comment]
I am working on gltf 2.o full conformance. Will update it then.

**Comment by xelatihy** [comment]
Hopefully fixed in the development branch.
