### ISSUE TITLE
[documentation request] GLTF C++ code generator from spec

### ISSUE THREAD

**Issue by KageKirin** [xelatihy/yocto-gl#20]
Hi again,

The `README.md` states that 
> yocto_gltf (.h/.cpp) - Khronos glTF loader and writer automatically generated by the spec.

So, I'm just curious to know which tool you are using for this.
Are you using the JSON Schema as base for the code gen?

Best regards.

**Comment by xelatihy** [comment]
Yes. I will release the new version within a week that includes the generator.

**Comment by KageKirin** [comment]
Great. Looking forward to the new version.

**Comment by xelatihy** [comment]
There is a preview in the development branch. I'll close. this.
