### ISSUE TITLE
Typo : doubled intersection

### ISSUE THREAD

**Issue by RisingDaystar** [xelatihy/yocto-gl#203]
https://github.com/xelatihy/yocto-gl/blob/36c349493fac3aa4bb6a8f60e16643a6b3d49537/yocto/ygl.cpp#L6364

I think there is a typo in the function, basically the intersection is performed twice, once at the beginning of the for loop , then at the end, with the last one having no impact on the computation since the variable is redefined at the beginning of the loop.

**Comment by xelatihy** [comment]
Thanks for catching. It is definitely a performance bug. Will be fixed in the next PR.
