### ISSUE TITLE
Error Compiling on VS2017

### ISSUE THREAD

**Issue by primesoftware** [xelatihy/yocto-gl#24]
I am getting the following errors when compiling on VS2017:

```
Error	C2512	'ym::vec<int,N>': no appropriate default constructor available	yocto	...\yocto-gl\yocto\yocto_gltf.h	1929

Error	C2039	'tolower': is not a member of 'std'	yocto	...\yocto-gl\yocto\yocto_utils.h	620	

Error	C2398	Element '1': conversion from 'double' to 'float' requires a narrowing conversion	yocto	....\yocto-gl\yocto\yocto_trace.cpp	1309	
```
There are more C2398's at lines 1309 for elements 2 and 3 as well. Ideas?

**Comment by xelatihy** [comment]
I'll look into this soon.

**Comment by xelatihy** [comment]
If you have fixes, please pull request them.

**Comment by siriusye** [comment]
can include ctype for tolower

**Comment by xelatihy** [comment]
Thanks - will do.

**Comment by lqzer** [comment]
When a default template function is invoked, the template function does not call the default value. When invoked, the actual parameter needs to be written with the default parameter value.
so when call this template function 
template <int N>
ym::vec<float, N> getv( int idx, const ym::vec<float, N>& def = ym::vec<float, N>()) const;

for example 
 keyframes->translation.push_back(output_view.getv<3>(i)); 
should modified to
 keyframes->translation.push_back(output_view.getv<3>(i, ym::vec<float, 3>()));
it can solve the constructor problem.
forgive me my poor English

**Comment by jingquanalex** [comment]
I have encountered these same errors compiling on my vanilla VS2017. Thanks for the fixes.
