### ISSUE TITLE
Full support for extensions

### ISSUE THREAD

**Issue by divis1969** [xelatihy/yocto-gl#25]
[myown.schema.json.txt](https://github.com/xelatihy/yocto-gl/files/1292158/myown.schema.json.txt)

[glTFmyextension.schema.json.txt](https://github.com/xelatihy/yocto-gl/files/1292154/glTFmyextension.schema.json.txt)
Hi,
I've tried to add some arbitrary extension to the list of JSON schemas (see the attachments) the ygltfgen is parsing and it looks like the generator does not create a code that can be easily used.
For this schema, it generates the types (struct glTFMyown; struct glTFmyextension;) but these cannot be used in a real gltf package example (see below) because those structs cannot referred from other structures or parsed from 'extensions' member of glTF.

The example contains:
```
   "extensionsUsed": [
        "myextension"
   ],
   "extensions": {
        "myextension" : {
            "myarray" : [
                {
                    "prop1" : "test",
                    "uri" : "SampleFile.txt"
                }
            ]
        }
    },
```

Is it possible to improve the generator?
Or am I misunderstanding of glTF extensions?

**Comment by xelatihy** [comment]
The generator will create new types for each extension, but you need to add a new variable name to the schema of the container object reference it. This is a limitation of the current generator, that, while it could be improved, it is unclear whether it is helpful since name clashes cannot be automatically avoided and need to be looked up manually. See the gltf Material schema.

**Comment by divis1969** [comment]
I would propose to improve it such a way that extension_t will also refer the parsed object (currently it refers the json, but the method to parse it is not visible from .h). Perhaps all these extensions could be inherited from common ancestor

**Comment by xelatihy** [comment]
I see what you mean. But that is equivalent to have untyped access (i.e. an untyped pointer). Whether that is much better than the JSON is to be seen. I got burned in the past but that type of architecture for another research parser we wrote.

**Comment by xelatihy** [comment]
In the meantime, is the extension that you need implemented a known one? I am soon taking another pass at the extensions to add some of the ones currently being worked on.
