### ISSUE TITLE
cmake linking error OS X

### ISSUE THREAD

**Issue by thewoz** [xelatihy/yocto-gl#26]
I have a linking issue on os x.

 To fix it I changed in the yocto folder the CMakeLists.txt from:

    if(APPLE)
        include_directories(/usr/local/include)
        link_directories(/usr/local/lib)
        find_library(GLFW_LIBRARY NAMES glfw3 glfw PATHS /usr/local/lib)
    endif(APPLE)

to:

    if(APPLE)
        include_directories(/usr/local/include)
        link_directories(/usr/local/lib)
        find_library(GLFW_LIBRARY NAMES glfw3 glfw PATHS /usr/local/lib)
        set(FRAMEWORK_COCOA "-framework Cocoa" CACHE STRING "Cocoa framework for OSX")
        set(FRAMEWORK_COREVIDEO "-framework CoreVideo" CACHE STRING "CoreVideo framework for OSX")
        set(FRAMEWORK_IOKIT "-framework IOKit" CACHE STRING "IOKit framework for OSX")
        set(FRAMEWORK_COREFOUNDATION "-framework CoreFoundation" CACHE STRING "CoreFoundation framework for OSX")
        set(GLFW_LIBRARY ${GLFW_LIBRARY} ${FRAMEWORK_COCOA} ${FRAMEWORK_COREVIDEO} ${FRAMEWORK_IOKIT} ${FRAMEWORK_COREFOUNDATION})
     endif(APPLE)

**Comment by xelatihy** [comment]
I'll close this since it applies to the previous version.
