### ISSUE TITLE
Windows with mingw64 crashes immediately becuase GL appears uninitialized.

### ISSUE THREAD

**Issue by tbogdala** [xelatihy/yocto-gl#3]
I got things up and running using [mingw64](https://msys2.github.io/).

yshade and ytestgen was built with these commands:

    gcc -std=gnu99 apps/yshade.c  -lglfw3 -lOpenGL32 -lglew32  -o bin/yshade
    gcc -std=gnu99 apps/ytestgen.c  -lglfw3 -lOpenGL32 -lglew32  -o bin/ytestgen

As described in the README files, I then generated the tests:

    bin/ytestgen.exe tests

Then I run:

    ./bin/yshade.exe --no-ui -r 480 -o tests/sh02.shade.png tests/sh02.obj

Which crashes at glCreateShader. This can be fixed by calling calling glewInit() first.

**Comment by samrat** [comment]
+1. Adding `glewInit()` also got rid of `yshade` segfault for me on Linux.

**Comment by xelatihy** [comment]
can you do a pull request on this?

**Comment by xelatihy** [comment]
Merging a new commit soon with a fix to this.
