### ISSUE TITLE
Missing library on MSVC 2017

### ISSUE THREAD

**Issue by MagicGreenDragon** [xelatihy/yocto-gl#38]
https://github.com/xelatihy/yocto-gl/blob/b1201906ec76e9deea1f176e5d7f9fe5f10fd461/apps/w32/include/GLFW/glfw3.h#L147

Visual Studio 2017 (on Windows 10) can't find this library, so the include fails.
Can I comment the include or I must install something?

**Comment by MagicGreenDragon** [comment]
Solved!

This is the simply solution:
- Download all OpenGL header files (glext.h, glcorearb.h, glxext.h, wglext.h) from the official website:
https://www.khronos.org/registry/OpenGL/index_gl.php#headers
- Put the downloaded header files into this folder:
C:\Program Files (x86)\Windows Kits\10\Include\um\gl\

Finally restart visual studio and now all the needed headers can be used.

**Comment by xelatihy** [comment]
This is fixed in the current release.
