### ISSUE TITLE
Compilation error C2864 with json.hpp

### ISSUE THREAD

**Issue by MarcoAndreozzi** [xelatihy/yocto-gl#40]
compiling as said in the readme.md leeds me to multiple line of C2864 error in  MVSC2017

**Comment by xelatihy** [comment]
What is the compilation error?

**Comment by MarcoAndreozzi** [comment]
the error is this one:
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c2864
the first one is in:
/json.hpp(812): error C2864: 'nlohmann::detail::has_mapped_type<T>::value': a static data member with an in-class initializer must have non-volatile const integral type

**Comment by xelatihy** [comment]
This is fixed in the current release.
