### ISSUE TITLE
Ubuntu 16.04 yview segment fault

### ISSUE THREAD

**Issue by xin-xinhanggao** [xelatihy/yocto-gl#42]
Thanks for your amazing job!

When I type the command 
`./ytrace tests/basic_pl/basic_pl.gltf ` 
I get the correct result.

But when I type 
`../bin/yview ../bin/tests/basic_pl/basic_pl.gltf`
I get the error info  Segmentation fault (core dumped)

I find the error occur in the yview.cpp line 169
`if (!is_program_valid(st->prog)) st->prog = make_stdsurface_program();`

My OpenGL version is 3.3, is it caused by OpenGL?

**Comment by xelatihy** [comment]
The shader code is OpenGL 3.3. Unfortunately debugging OpenGL on different system is an excercise in frustration since there is no real standard. I do not know how I can help more with this.

**Comment by xin-xinhanggao** [comment]
Still thanks for your warm heart, I will try to fix it by myself.
