### ISSUE TITLE
delta tracking

### ISSUE THREAD

**Issue by giacomonazzaro** [xelatihy/yocto-gl#430]
We currently have old code for rendering heterogeneous volumes using delta tracking.
Consider whether is worthwhile reusing it or not.

If that is the case, it should be in a different tracer, but it may be possible also to integrate it into the main renderer and switch to the different code path only if `volume_texture != -1 `.

**Comment by giacomonazzaro** [comment]
Delta tracking could be easily integrated by taking the following assumption:
heterogeneous volumes cannot have spectrally varying density (they can still have colored volume albedo, which only affects scattering, not interaction probability).

**Comment by xelatihy** [comment]
I'll close this until we do it.
