### ISSUE TITLE
Sharing of big scenes

### ISSUE THREAD

**Issue by giacomonazzaro** [xelatihy/yocto-gl#432]
The entire dataset of the scenes is hundreds of gigabytes. We must find a way of sharing it easily.

**Comment by xelatihy** [comment]
Here are the TODOs for this to get to v1 with scenes.

- [ ] conversions
    - [ ] convert all pbrt scenes to OBJ unless they have instancing
    - [ ] convert all pbrt scenes to JSON so we can support instancing
        - [ ] or add instancing to our OBJ extensions
    - [ ] convert all obj to our JSON (this is just a convenience)
    - [ ] convert all pbrt to our JSON (this is just a convenience)
- [ ] pack all scenes for backup and deployment
    - [ ] scenes now are packed as one with multiple formats overlapping
        - we might need to undo this and have formats be self-contained
        - this also makes it more clear whether the conversion works or not
        - but it will take up more space and more time
- [ ] Disney island will be backed up as ybin and reconverted every time
