### ISSUE TITLE
Total internal reflection

### ISSUE THREAD

**Issue by giacomonazzaro** [xelatihy/yocto-gl#452]
Total internal reflection is not implemented. This causes noticeable energy loss with refractive materials.

We should decide whether we want to implement it or not, considering the fact that it could increase the complexity of the brdf code.

**Comment by xelatihy** [comment]
We should. In the THIN version I recall there was an elegant way to handle it. Not sure in the new version.

**Comment by xelatihy** [comment]
This should be fixed now.
