### ISSUE TITLE
Objs not readable from other applications.

### ISSUE THREAD

**Issue by antoniomuso** [xelatihy/yocto-gl#47]
Objs created by yocto aren't readable by other application. I enter the error given by Blender when I import obj:

> Traceback (most recent call last):
  File "/usr/share/blender/scripts/addons/io_scene_obj/__init__.py", line 147, in execute
    return import_obj.load(context, **keywords)
  File "/usr/share/blender/scripts/addons/io_scene_obj/import_obj.py", line 1182, in load
    unique_material_images, use_image_search, float_func)
  File "/usr/share/blender/scripts/addons/io_scene_obj/import_obj.py", line 344, in create_materials
    context_material.specular_hardness = int((float_func(line_split[1]) * 0.51) + 1)
ValueError: bpy_struct: item.attr = val: Material.specular_hardness value not in 'int' range ((-0x7fffffff - 1), 0x7fffffff)
location: <unknown location>:-1

**Comment by OrangeNote** [comment]
Set material roughness to an integer value, like this: `mat->rs = 0;`

The default value in the source code is causing the issue:
```
/// roughness
    float rs = 0.0001;
```

**Comment by antoniomuso** [comment]
I have tried but it doesn't work.

**Comment by OrangeNote** [comment]
Did you try to set `float rs = 0;` then? Maybe you skipped some values in your code... it worked for me on different machines.

**Comment by antoniomuso** [comment]
yes, you are right. Now, it works.
