### ISSUE TITLE
Light source Type

### ISSUE THREAD

**Issue by xin-xinhanggao** [xelatihy/yocto-gl#53]
Can yocto-gl support the directional light source?

I am sorry that now I only find the env light, point light and area light.

**Comment by xelatihy** [comment]
So far, directional lights are supported only in the glview but not in the tracer code.
My suggestion is to put a point light far away and set its Ke to distance^2 * Ke.

**Comment by guillaumechereau** [comment]
Hello, I would like to reopen this issue, since it's not very clear to me how to get directional light in the current version of the code.  Adding a point shape doesn't seem to be picked up as a light.  I can add a small far way triangle, but I would like to make it invisible if possible.  Can environments be used to achieve this?

**Comment by xelatihy** [comment]
Right now, yocto support triangles, quads and environment lights. This is done to ensure a faster rendering with MIS which uses a sampling strategy that is quite different than other renderer. We always sample all lights, instead is sampling individual lights.

You can make a directional lights in either of two way:
1) an envmap with only a few pixels lit
2) a quad light far away

I would probably do (2).

**Comment by guillaumechereau** [comment]
Right, this is what I am doing at the moment (I give an other shot at integrating yocto into goxel voxel renderer).  I guess that will be enough, though I wished I could ensure that the light quad would never get rendered even if the camera point in its direction.

**Comment by xelatihy** [comment]
I see what you mean. Right now yocto is designed as a physically-based renderer so we do not support unphysical renderers. If the integration feels like it works, I can add a small custom renderer to your spec. This is what we do in our internal research projects and it works great.

**Comment by guillaumechereau** [comment]
No worries.  I think the current code will be enough for now.  I really like the async rendering, it seems much easier to integrate compared to cycles.

**Comment by xelatihy** [comment]
I am planning to clean that up a bit and make it even easier to use. I'll post something here when done.
