### ISSUE TITLE
Weight about path tracing

### ISSUE THREAD

**Issue by xin-xinhanggao** [xelatihy/yocto-gl#54]
Maybe the line 6256 of  yocto-gl/yocto/yocto_gl.cpp

`weight *= eval_brdfcos(pt, wo, bwi) * weight_brdfcos(pt, wo, bwi);`

should be changed to

`weight *= eval_brdfcos(pt, wo, bwi, bdelta) * weight_brdfcos(pt, wo, bwi, bdelta);`

because bwi is sampled with bdelta together.

**Comment by xelatihy** [comment]
You are right. Fixed in dev branch. Thanks.
