### ISSUE TITLE
image resolution in ytrace

### ISSUE THREAD

**Issue by edoardocarra** [xelatihy/yocto-gl#581]
camera_resolution method in ytrace set the wrong image resolution. There should be a bug in this snippet of code in yocto_scene.cpp:  
METHOD: vec2i camera_resolution(const yocto_camera& camera, const vec2i& size_)

`  
    if (size.x * camera.film.y / camera.film.x > size.y) {
      size.x = 0;
    } else {
      size.y = 0;
    }
`

**Comment by xelatihy** [comment]
Fixed in #584
