### ISSUE TITLE
Russian Roulette

### ISSUE THREAD

**Issue by RisingDaystar** [xelatihy/yocto-gl#603]
In yocto_trace , il criterio di terminazione della russian roulette é del tipo random > std:max(0.05,1.0-max(w)) .
Non dovrebbe essere "random < ...  " ? , 
con la formula attuale tende (se non erro) a terminare i sample che possono contribuire maggiormente ... (ex: se sample max(w)=0.9 , 1.0-0.9 = 0.1 , c' é una probabilitá alta che random sia > 0.1)

**Comment by xelatihy** [comment]
Do' un'occhiata appena ho tempo.
