### ISSUE TITLE
yocto_random.h compiler error.

### ISSUE THREAD

**Issue by PuscasuRobert** [xelatihy/yocto-gl#631]
In the file yocto_random.h at line 124 you have the code :
         return (xorshifted >> rot) | (xorshifted << ((-rot) & 31));

But the variable rot is of type uint32_t and using the minus operator in front of a unsigned variable gives unexpected behavior in C++.  VC2017 sees this as a error, not just a warning. Maybe you wanted to type:
        return (xorshifted >> rot) | (xorshifted << ((-int(rot)) & 31));
But im not sure, so please answer.

**Comment by xelatihy** [comment]
Note sure why this was not matched by our CI. Having said that the code comes from 
http://www.pcg-random.org/download.html#minimal-c-implementation
Can you take a look if this fixes it?

**Comment by PuscasuRobert** [comment]
The code has the same error: they use  "-rot" in their code but the variable rot is unsigned.

**Comment by PuscasuRobert** [comment]
Maybe their compiler automatically convertes between int and unsigned int without caring of losing data. I think all you need to do is replace "-root" with "-int(root)"

**Comment by xelatihy** [comment]
I close this isse since it is stale and cannot reproduce it.
