### ISSUE TITLE
Split scene

### ISSUE THREAD

**Issue by xelatihy** [xelatihy/yocto-gl#676]
We are considering splitting the main yocto scene into multiple scenes to enable applications to tailor the data they handle and reduce dependencies between libraries/files. The branch split_scene tracks effort in this space.
In doing so thought, there are many design decisions that need addressing and that we report below.

- [x] decide sceneio file
    - right now we have sceneio in its separate file
    - right now we call scene loading elements scene_shape, scene_material, scene_model
    - right no
    - [x] should yocto_sceneio be merged into yocto_modelio?
        - now sceneio is in its separate file
    - [x] scene_XXX naming convention is real bad; any idea for a better name prefix? sceneio_XXX? (still horrible, but slightly clearer)
        - now scene_XXX naming convention
    - [x] should load_shape/save_shape, load_image/save_image move to yocto_modelio so that all loading is in one place?
        - right now loading is split and there are cyclic dependencies between modelio and shape
        - benefit all io in one place
        - drawback, image inside all 3d stuff
    - [ ] any ides where to put subdivision/displacement of sceneio.shapes? maybe the applications?
- [x] trace scene
    - [x] should lights be separate objects or included in the scene?
        - the benefit of this is that the scene is "read only"
        - the badness is that we have separate functions and a separate structure, trace_lights, to move lighting information around
    - [x] should bvh be separate objects or included in the scene?
        - right now the bvh is external with weird sharing of references
        - moving it inside the scene or as a side car without reference sharing would make the code way better
    - [ ] we have a ton of small functions now that are there either because they had long calling tress or to provide services to other applications; shorten this
    - [x] should we have all sampling code here?
    - [x] should we move inside all sample_XXX functions instead of using yocto_random?
       - main reason here is code simplicity and locality
- [x] dependencies
    - we should strive to have yocto_XXX files as independent as possible from one another
    - [x] should we split yocto_random?
        - rng_XXX -> math, sample_XXX -> yocto_trace/yoct_shape, Perlin -> yocto_math ?
    - [x] should we either move image<T> to yocto_math or sometimes store images as size+pixels?
        - image<T> is often a dependency only to store image data and might not even require any actual code to be called
- [x] namespaces
    - right now all code is under the same namespace with the usual name clash issues
    - [x] should we introduce namespaces in the code? one per file?
        - benefit: no name clashes
        - benefit: shorter names for objects (we do not need trace_model, obj_model, sceneio_model, etc)
        - drawback: not tried
        - drawback: maybe a little more verbose, but we've got using directives ...

**Comment by giacomonazzaro** [comment]
- Should yocto_sceneio be merged into yocto_modelio?
Yes, it can be named `yocto_io.h`

- Should load_shape/save_shape, load_image/save_image move to yocto_modelio so that all loading is in one place?
No. From the user side, it is better to get with a single include both the manipulation of some data together with the io of that same data.

- Should lights be separate objects or included in the scene?
Since now we have specialized scenes, it is better to put lights and bvh inside trace_scene.

- Extra
The definition of the shape struct is not in yocto_shape.h, which can be confusing.
Maybe we can rename `yocto_shape.h` into `yocto_geometry.h` since it actually implements geometry processing and manipulation.

**Comment by giacomonazzaro** [comment]
- Should we either move image to yocto_math or sometimes store images as size+pixels?
We could put `image<T>` in `yocto_math`, as a 2D container.
All the rest (color-related code + loading/saving) in image
