### ISSUE TITLE
Support for orthographic projection

### ISSUE THREAD

**Issue by guillaumechereau** [xelatihy/yocto-gl#8]
Is there a way to generate an image rendered using an orthographic projection?
I think it should be simple to modify yt__eval_camera to support this case, not sure how the API should handle it though.

**Comment by xelatihy** [comment]
It would be quite easy. I am in the middle of changing the internal implementation of yocto, so I can't do it right away. From an API standpoint, I could just add an orthographics flag to yt_set_camera.

**Comment by guillaumechereau** [comment]
Thanks!  I'll keep an eye on it.
