### ISSUE TITLE
Scene property names

### ISSUE THREAD

**Issue by xelatihy** [xelatihy/yocto-gl#831]
We should freeze all property names used in the scene file format. The left over open issues are

- [ ] choose texture names
    - right now we use `<property>_tex` in `sceneio` and `<property>_map` everywhere else
    - we should choose between `<property>_tex`, `<property>_map` or `<property>map`
    - I prefer ending with `map` and maybe `<property>map`, but also `<property>_map`
- [ ] choose name for instance element in ply
    - right it is called `frame` but that means we cannot add anything else after
    - I propose to use `instance` that is similar to the convention used for meshes that have `face` and `vertex` elements
- [ ] we should list any other property name we do not like and fix now or leave for the future

**Comment by giacomonazzaro** [comment]
While _normalmaps_, _specularmap_ are more colloquial terms, we must consider that names ending with `map` are often used to represent mapping or bijections between objects. For example in `init_scene()` of apps there are a lot of _maps_ which are just hashmaps.

Names endings with `tex` are more pedantic but they clearly show that we are talking about **tex**tures.

In both cases, using `snake_case` with the underscore is more consistent with the rest of the library.

There are some instances of `<property>_txt` in the codebase, which should be avoided as they may suggest something about `.txt` or text in general.

**Comment by xelatihy** [comment]
Let us then settle on the convention of `<property>_tex`. I will update the majority of the codebase for this.

**Comment by xelatihy** [comment]
Fixed in #835
