### ISSUE TITLE
Scene dictionaries and paths

### ISSUE THREAD

**Issue by xelatihy** [xelatihy/yocto-gl#832]
Right now `sceneio` uses arrays to store objects. The file names used in IO are written in the object `name` property. This has two main issues:

- there are no checks on whether two object have the same filename
- there are no checks on whether the file names are valid
- (less important maybe) you can organize the scene in any way you want; but this also means that you are welcome to shoot yourself in the foot and you have to be very careful when writing scenes programmatically

There are two possible fixes for all these issues and we should choose whether doing them or not.

- [x] use dictionaries both in the file format and `sceneio` data structure to indicate object
    - pros: force file names to be unique; file names and file contents are not mixed in the data structure (just like on disk); in SceneGit we concluded that this was necessary, but that was arguably a different application
    - cons: we do not keep the order of objects
- [x] use names and not paths in the `sceneio` data structure; in fact, do not even preserve paths on load
    - on save: construct file names from the name, like `shapes/shape_<name>.ply`
    - on load: look for files in the predefined directories, appending the needed extension; if this fails, look for compatible extensions, but only in the give directories

**Comment by giacomonazzaro** [comment]
The first approach looks less error-prone, which is important while trying to quickly set up a scene.
Enforcing a convention on files should not create too much friction if it is well documented and error reports are clear.

**Comment by xelatihy** [comment]
We have implemented the name component of the proposal. For the dictionary component, we have implemented dictionaries in the file format, but not the in memory representation. This was to ensure that we do not encounter scalability issues with the use of `std` dictionaries.
