### ISSUE TITLE
Should normals/texcoords be always present?

### ISSUE THREAD

**Issue by xelatihy** [xelatihy/yocto-gl#839]
Right now both the path tracer and the opengl renderer assume that normals may or may not be present. This means that there are a lot of possible code paths that are rarely used but never tested properly. We should decide whether it makes sense to force a convention on this, like that normals should alway be present at least on the GL and trace renderers.

- [ ] decide whether normals shoudl always be preset
- [ ] decide whether texcoords should always be present

**Comment by giacomonazzaro** [comment]
Force the presence of *normals* is a sound assumption, as normals are a fundamental property of surfaces and can always be computed from the geometry.

I'm not sure about texcoords. They are not as important as normals, but they would remain the only exception (assuming we enforce normals). Uniformity would probably benefit from assuming also the same convention on texcoords.

**Comment by xelatihy** [comment]
It makes sense to do normals and not texcoords. We will phase this out slowly over the next days. This will mostly come as code simplification across trace, gl and loader.

**Comment by xelatihy** [comment]
To release v2, we postpone this to later.
