### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [xelatihy/yocto-gl#899]
I would like to point out that identifiers like “[`_GLFWerror`](https://github.com/xelatihy/yocto-gl/blob/10e185c65654a4edb84ffc857851ecac15ba998f/libs/yocto_gui/ext/glfw/src/internal.h#L63 "Update candidate")” and “[`_YOCTO_IMAGE_H_`](https://github.com/xelatihy/yocto-gl/blob/d0db0ff47fd9ab8c0739267335e66a039acb928e/libs/yocto/yocto_image.h#L92 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by xelatihy** [comment]
This is an imported external project. So will keep it this way.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
