### ISSUE TITLE
Remove unnecessary checks for API handles

### ISSUE THREAD

**Issue by elfring** [xelatihy/yocto-gl#900]
[Extra checks are not needed for zero API handles in a function](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glDeleteProgram.xhtml "Delete a program object.") like [the destructor for the class “image”](https://github.com/xelatihy/yocto-gl/blob/d0db0ff47fd9ab8c0739267335e66a039acb928e/libs/yocto_gui/yocto_gui.cpp#L326 "Update candidate").

**Comment by xelatihy** [comment]
We can certainly do this for next release.

**Comment by xelatihy** [comment]
We can certainly do this for next release.

**Comment by xelatihy** [comment]
I am closing this and reopen it once we start to work on version 3.
