### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [xelatihy/yocto-gl#901]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [app_state](https://github.com/xelatihy/yocto-gl/blob/10e185c65654a4edb84ffc857851ecac15ba998f/apps/ysceneview/ysceneview.cpp#L93 "Destructor for app_state")
- [init_bvh](https://github.com/xelatihy/yocto-gl/blob/7ba6e2cc6837ccd84bdc4402f44c0992ec2be61e/libs/yocto/yocto_trace.cpp#L1251 "init_bvh function")

**Comment by xelatihy** [comment]
Thanks. This is something that we could then do. In the past though, some architecture had crashes. But I think this should work on new compilers. I'll clean this up next release.

**Comment by xelatihy** [comment]
I am closing this and reopen as we start to work on version. 3.

**Comment by elfring** [comment]
How do you think about to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by xelatihy** [comment]
I'd love too. But how is it done on Mac? Could not find an easy installation path via Homebrew,  but if you know of one, I would love to hear it,
