### ISSUE TITLE
load_text() fails on Windows

### ISSUE THREAD

**Issue by Hurleyworks** [xelatihy/yocto-gl#903]
Thanks for making such a great looking project available!

I've compiled the latest github version of yocto-gl on Windows 10 using Microsoft Visual Studio Community 2019 Version 16.5.0 and am unable to load any of the json test scenes because of a failure in  load_text() on line 949 in yocto_sceneio.cpp 

 **if (fread(str.data(), 1, length, fs) != length) return read_error();**

**Comment by xelatihy** [comment]
We have a lot of Windows users that did not report the problem. So it may be hard to reproduce. Can you tell me on which test this happens? Also can you report the command line for it? For example

```
[yocto_gl] ./bin/ysceneitraces tests/features1/features1.json
```

**Comment by Hurleyworks** [comment]
It happens on all tests loading .json files.

I think I found the problem on line 942 of yocto_sceneio.cpp
 **auto fs = fopen(filename.c_str(), "rt");**

"rt" is not a valid file access mode. If you change it to "rb" then the problem goes away and loading works as expected

**Comment by xelatihy** [comment]
Yes. I did a quick fix that is a little bit different, but I think I am going to stick to your solution. I will upload a new version shortly.

**Comment by xelatihy** [comment]
Your fix should be on master now. Thanks!
