### ISSUE TITLE
Adaptive Sampling.

### ISSUE THREAD

**Issue by mkanada** [xelatihy/yocto-gl#917]
Please, take a look at my implementation of 'Adaptive Sampling', using yocto-gl. I do my best to not change too much the original code, just adding a new one. So, the integration may be easy, if you think it is useful.

https://github.com/mkanada/yocto-gl

**Comment by xelatihy** [comment]
Very nice results! I would love to get this integrated in. Right now it seems that a PR would modify a lot of code.

What do you think we need to d to get this in? And in particular, are there changes I could make in yocto to make it easier to get your work in? Alternatively, would we integrate a new renderer in that uses all transport code from Yocto and a new path tracer main-loop? 

Incidentally, I was planning to modify the trace APIs and always render one full image worth of samples. This would make a lot of code simpler. Would that help? 

Let me know and let us see if we can get your work in.

**Comment by xelatihy** [comment]
Very nice results! I would love to get this integrated in. Right now it seems that a PR would modify a lot of code.

Quick question: do you think I could just integrate the yocto adaptive path tracer and the two new apps. I mean to get your work in, can I just integrate `yocto_trace_adp.{h,cpp}` and `apps/*.adp`? I noticed other changes to math and such that I might be able to replicate on my branch.

In case it would, would you be with the integration and to release it at MIT license?

**Comment by mkanada** [comment]
To me, the licence is irrelevant. This is just fun.

About the applications, 'yscenetrace_adp' is important, but 'ysceneitraces_adp' no. The second one is far from mature. About the math, I think that you will jump to template based in some time in the future, and I do this jump now. And created 'double' version of 'vec*', but it was useless. So, math changes is irrelevant.

**Comment by xelatihy** [comment]
Ok. I’ll see if we can push it in over the weekend

**Comment by xelatihy** [comment]
We will postpone the merge to the new release.
