### ISSUE TITLE
Merge Yocto/Realtime

### ISSUE THREAD

**Issue by xelatihy** [xelatihy/yocto-gl#922]
Yocto/Readltime provides significantly better OpenGL support, but with slightly different interfaces.
We should merge most of Yocto/Realtime into Yocto/GUI, but do so without disruption to the current applications that have been already extensively debugged. The only changes we plan is to adopt yocto use of explicit pointers, instead of references, for object that manage state.

**Comment by giacomonazzaro** [comment]
Link to the repo for future reference
https://github.com/giacomonazzaro/realtime

**Comment by xelatihy** [comment]
Partial merge of ideas in #924

**Comment by xelatihy** [comment]
Duplicate of #981
