### ISSUE TITLE
Split Yocto/Math

### ISSUE THREAD

**Issue by xelatihy** [xelatihy/yocto-gl#935]
This issue track ideas on how to split Yocto/Math. Right now math contains a lot of different functions that are int eh following categories

- linear algebraic types vec/mat/frame/transforms
- color manipulation on vec
- geometry types ray/bbox/intersection/overlap
- random number generation
- noise
- Monte Carlo helpers
- brdf/phasefunc Monte Carlo helpers

We probably want to split Math into two or more files. This issue track proposal on how to do this.

**Comment by xelatihy** [comment]
One possibility would be to split in three files:

- math: vec/mat/frame, transforms/color
- geometry: ray/bbox/intersection/overlap
- Montecarlo: Monte Carlo helpers, brdf/phasefunc

not clear where to put 

- rng
- noise

also not clear what names we want

**Comment by giacomonazzaro** [comment]
Alternative split worth considering:

`yocto_math`: math + geometry. Rays, bbox and intersections are common enough to be included in the general-purpose math library. `yocto_math` is everything you need for operations in vector spaces.

`yocto_random`: rng, noise and shape sampling (sphere, triangle, disk...). No brdfs here: you don't need them unless you're shading something, plus that code is big and complex. It is better to isolate it.

`yocto_brdf/yocto_shading`: brdf sampling, evaluation, pdf, delta handling, fresnel, eta conversion, phase function.

Everything can be header-only.

**Comment by xelatihy** [comment]
I do not mind this last design. Where should we put all Monte Carlo helpers? In yocto_random o yocto_shading?

**Comment by giacomonazzaro** [comment]
We can put them into yocto_random, since those operation are often useful in problems different than shading. (namely: sampling for disk, cylinder, triangle, sphere, hemisphere, hemisphere_cos, hemisphere_cospower, uniform, discrete).

yocto_shading only for eval/sampling/pdf of microfacet, diffuse, transmission, deltas, phasefunction (shading does not depend on yocto_random).

**Comment by xelatihy** [comment]
I think this makes sense. I will slowly start to split them up.

**Comment by xelatihy** [comment]
Fixed in #954
